### ISSUE TITLE
Backup

### ISSUE THREAD

**Issue by Brandl** [zyrill/android_device_lenovo_b8080h#1]
Hey,

found this highly interesting project by accident.

I'm interested in your progress so far. Is it possible to make a backup of the stock Android and go back to the factory settings? Do you consider this safe and stable?

Thanks a lot.

**Comment by zyrill** [comment]
Sorry, don't check my git email account too often. Yes, it's possible to do
a backup and you can also go back to the factory settings. A few people
have tried it out and nobody had major problems. It's best if you check the
XDA forum thread. All the best and merry christmas!

2014-08-02 18:00 GMT+02:00 Brandl notifications@github.com:
