### ISSUE TITLE
Lenovo b8080-f

### ISSUE THREAD

**Issue by boydkelly** [zyrill/android_device_lenovo_b8080h#2]
Hi,
Any idea what the difference is between b8080-h and b8080-f?  I have the latter and want to make sure I won't have any problems to install a custom rom.  Thanks!

**Comment by zyrill** [comment]
I haven't been working on this project for years so I don't remember too well, but the difference is in the baseband if memory serves. To be absolutely clear: I have no idea if you can still use my project on recent firmwares and OS versions. Proceed with extreme caution. Basically, you should only use this if you're a kernel hacker.

**Comment by zyrill** [comment]
I googled and this is what I found regarding the difference between h and f. There's some more links in the thread I linked with tech specs. HTH!
https://forums.lenovo.com/t5/Lenovo-Android-Tablets/Unterschied-zwischen-B8080-H-und-B8080-F/td-p/3354765
